main:
  method: 'get'
  path: ~
  controller: App\Controller\HomeController
  action: index

show:
  method: 'get'
  path: show/{id}
  requirements:
    id: '\d+'
  controller: App\Controller\HomeController
  action: show